# Aims

The misspecification of the distributional assumption of the Concordance Correlation Coefficient has led to the exploration of two avenues in order to address it: Fit an appropriate model and update the coefficient's formula accordingly (@carrasco2009a), or to find robust methods of estimation of the coefficient (@king2001, and @feng2018). In this thesis the focus will be placed on the latter, which has been the main line of study in the literature (already in the coefficient's proposal, Lin tested the robustness the coefficient under misspecification of the distribution), comparing the robustness (through coverage and bias) of different estimation methods that have been expanded or proposed since @carrasco2007. These methods will be compared in a simulation study under five different levels of longitudinal concordance, and three levels of skewness.

The impact of transformations of the data, in particular the log-transformation, in order to obtain normality and its connection to the correlation coefficient, will be assessed in the first case study, a small dataset with moderate skewness of bacterial colony formations in paired molar samples. The second case study  will review a large longitudinal dataset with time-varying concordance, potential covariates, and a significant dropout process, where possible under or overspecification has been reviewed, accompanied with an assessment of the impact of the observed missing pattern on the estimation methods.